### ISSUE TITLE
How to Use treeselect.js in a Project with HTML, CSS, and JavaScript (No Frameworks)

### ISSUE THREAD

**Issue by omar-shaheen** [dipson88/treeselectjs#118]
I am working on a project using only HTML, CSS, and vanilla JavaScript (no frameworks like Vue.js or React). I would like to integrate treeselect.js into my project. Can someone provide an example of how to do this? 🙏

**Comment by Romans96** [comment]
Hello! It's just explained in the main project page.

Import in the head, or in the end of the body the js script and the css file:
```
<script src="https://cdn.jsdelivr.net/npm/treeselectjs@0.11.0/dist/treeselectjs.umd.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/treeselectjs@0.11.0/dist/treeselectjs.css" />
```

(if your project does not accept online link open them and creates two local files with that code like and import them like
```
<script src="/js/treeselectjs.umd.js"></script>
<link rel="stylesheet" href="/css/treeselectjs.css" />
```

Than in any script tag or in any external .js file you can use the Treeselect object to init your dropdown
```
...
<body>
  <div id="dropdowntest"></div>
</body>
<script>
  ...
  const treeselect = new Treeselect({ 
    parentHtmlContainer: document.getElementById("dropdowntest"),
    value: [1,2],
    options: [
      {
        name: "test1",
        value: 1,
        children: [],
      },
      {
        name: "test2",
        value: 2,
        children: [
           {
              name: "test2-2",
              value: 3,
              children: [],
           },
           ...
        ],
      },
    ],
  });
  ...
</script>
```

**Comment by dipson88** [comment]
@Romans96 Thank you for your help to @omar-shaheen. This example should work fine.

**Comment by omar-shaheen** [comment]
@Romans96 Thank you the method works well. ❤️
