### ISSUE TITLE
Suggest documentation enhancement: describe what the {options.value} property does.

### ISSUE THREAD

**Issue by mflanagan** [dipson88/treeselectjs#15]
It's not obvious what the `value` property in the `options` object does. Currently, it simply says, "It is an array with ids." Perhaps it should say something such as, "An array of `value` ids that will be selected when the dropdown is loaded (upon `mount(),`" or something like that.

**Comment by dipson88** [comment]
Hi @mflanagan, I agree with you, I will update README in the next release. I will try to update the description for this prop in a more understandable way.
