### ISSUE TITLE
Module parse failed: Unexpected character '#' (1:2341)

### ISSUE THREAD

**Issue by arpit1984** [dipson88/treeselectjs#22]
I installed treeselectjs via npm and I am using it with polymer3.
Though when I build my application, I am getting following error:
_Module parse failed: Unexpected character '#' (1:2341)_

My webepack.config.js is 

```

const merge = require('webpack-merge');
const flowDefaults = require('./webpack.generated.js');


module.exports = merge(flowDefaults, {
        mode: 'production',
        module: {
                rules: [
                        {
                          test: /\.svg$/,
                          use: {
                            loader: 'html-loader',
                            options: {
                              minimize: true
                            }
                          }
                        },
                        {
                                test: /\.js$/,
                                loader: 'ify-loader'
                        }
                        ]
        },
        stats: {
          warnings: false
        }
});
```

How this can be resolved?

**Comment by dipson88** [comment]
Hi @arpit1984, I think it related to the wrong build process. I used build for node instead of browser. I fixed this issue in new version 0.3.2. Could you please download the new version without of '#' signs? Please notify me if the problem still reproduces.

**Comment by arpit1984** [comment]
This solved the issue and build fine. Though I am seeing other errors. Following is my code:

```
import {normalizeWorkspaceDict} from '../../global-functions.js';
import { PolymerElement, html} from '@polymer/polymer/polymer-element.js';
import {afterNextRender} from '@polymer/polymer/lib/utils/render-status.js';


import { Treeselect } from 'treeselectjs';

class WorkspaceSelector extends PolymerElement {
    static get template() {
        return html `
            <style>
                #workspace-select {
                    width: 100%;
                }
                .sciome-select {
                    font: 400 16px "acumin-variable-concept";
                    padding: 5px;
                }
                
            </style>
            
           <div id ="test" class="sciome-select"></div>
`;
    }

    constructor() {
        super();
    }
    
    ready() {
        super.ready();
        var self = this;
        const options = [
        	  {
        	    name: 'England',
        	    value: 'England',
        	    children: [
        	      {
        	        name: 'London',
        	        value: 'London',
        	        children: [
        	          {
        	          name: 'Chelsea',
        	          value: 'Chelsea',
        	          children: []
        	          },
        	          {
        	          name: 'West End',
        	          value: 'West End',
        	          children: []
        	          }
        	        ]
        	      },
        	      {
        	        name: 'Brighton',
        	        value: 'Brighton',
        	        children: []
        	      }
        	    ]
        	  },
        	  {
        	    name: 'France',
        	    value: 'France',
        	    children: [
        	      {
        	        name: 'Paris',
        	        value: 'Paris',
        	        children: []
        	      },
        	      {
        	        name: 'Lyon',
        	        value: 'Lyon',
        	        children: []
        	      }
        	    ]
        	  }
        	]
        const domElement = this.$["test"];
        const treeselect = new Treeselect({
        	  parentHtmlContainer: domElement,
        	  value: ['West End', 'Paris', 'Lyon'],
        	  options: options,
        	  
        	})
}
```


When I am clicking on dopdowns, it is throwing the errors:

_TypeError: Cannot read properties of null (reaching' checked')
TypeError: Cannot decontruct property "groupedNodes' of 't.detail' as it is undefined._

I am new to polymer 3, so very possible I am doing something wrong

**Comment by dipson88** [comment]
@arpit1984 Could you say what exactly place you click? Or send a screenshot of the place. I think there can be a problem with CustomEvent in polymer, but I didn't work with polymer. Could you create a CustomEvent (new CustomEvent('test', { detail: 'test' }) inside of your code, for example. In the feature I am going to remove CustomEvents from my the component.

**Comment by arpit1984** [comment]
![image](https://user-images.githubusercontent.com/58046938/181574961-81e65afb-3817-4671-aa6e-addcc036b39f.png)

The dropdown somehow is transparent and overlays on the the background button. When I click one of the checkboxes, then I get the following errors. 

![image](https://user-images.githubusercontent.com/58046938/181575203-8bce8c9f-5e09-4936-b6b6-610ffd171f1b.png)


I am new to polymer 3, so dont know about customevents. Let me look into this

**Comment by dipson88** [comment]
@arpit1984 I see, I reproduced this, probably I know the solution. So there is a problem with styles and position of elements. Styles help me create a right position of elements. So could you add styles from dist, you can check README. Styles will help you.

**Comment by dipson88** [comment]
You can rewrite styles for your site, with the help of CSS classes.

**Comment by arpit1984** [comment]
Very stupid question. can you tell me how to import styles in above class.
I tried <link href="treeselectjs/dist/treeselect-js.css" rel="stylesheet"> but that doesnt work

**Comment by dipson88** [comment]
I found this ```<link rel="import" type="css" href="my-awesome-button.css">```
https://polymer-library.polymer-project.org/1.0/docs/devguide/styling.html#style-modules
But it is deprecated. I don't know how a polymer works. You need a google something like 'How to add a style from package polymer'. Maybe it can be helpful too, but I don't sure. https://stackoverflow.com/questions/36224425/custom-style-vs-shared-styles-in-polymer

**Comment by arpit1984** [comment]
Thanks. I am working on it. Do you have any idea about the issue it was throwing 
![image](https://user-images.githubusercontent.com/58046938/181583945-888c69cd-bc09-4fc6-858d-4d4f1b14199e.png)

Or you meant that css style will solve the issue?

**Comment by dipson88** [comment]
@arpit1984 Yeh, styles should fix this issue. I reproduced this issue on my side. Then I added styles, and the issue was fixed. I think styles should help.

**Comment by arpit1984** [comment]
I am using all the css styles from your package as inline in my app and I see some of the styles are in action, but still I am seeing the above mentioned error and transparent drop down. As some of the styles are working, I wonder if css isnot missing anything. Following is the updated image. The serach bar and the items in search bar looks fine, but the drop down still messed up
![image](https://user-images.githubusercontent.com/58046938/181839492-8dbe87eb-ff27-4058-a625-c567b91566da.png)

**Comment by dipson88** [comment]
Could you show how did you add styles, because I don’t fully understand what inline means. Because partly applying looks strange, css file contains all styles for the list and for the input.

**Comment by arpit1984** [comment]
Thank you for all the help. I tried multiple ways of adding css to my app. Then I thought to use the crude approach and I copied the content of three css files under src folder of the github directly in my app like:
```

class WorkspaceSelector extends PolymerElement {
    static get template() {
        return html `
            <style>
            	
            	.treeselect {
  width: 100%;
  position: relative;
  box-sizing: border-box;
}

.treeselect--disabled {
  pointer-events: none;
}

.treeselect-list {
  position: absolute;
  left: 0;
  border-radius: 4px;
  box-sizing: border-box;
  z-index: 1000;
}

.treeselect .treeselect-list {
  position: absolute;
}

.treeselect .treeselect-list--static {
  position: static;
}
...........
```

I also tried to copy the css content from treeselectjs/dist/treeselect-js.css directly to the app, but got only partial effect.

**Comment by dipson88** [comment]
So, I have only one idea. Maybe something went wrong during the copying. I can give you a treeselect-js.css file with the right formatting. It can help, I think. File is here https://drive.google.com/file/d/1Z60m9MllZEunmw96l4u91WV5xjL90eiX/view?usp=sharing
But in the feature, when you understanding how to connect CSS, use CSS from the dist of the package.

**Comment by arpit1984** [comment]
Thanks, I tried but it is same result. I am also clueless what might be happening

**Comment by arpit1984** [comment]
i dont use listSlotHtmlComponent.  Do you think that could be the reason. I use it like:


 ```
  <div id ="test" ></div>
....
...


const domElement = this.$["test"];
const treeselect = new Treeselect({
        	  parentHtmlContainer: domElement,
        	  value: ['West End', 'Paris', 'Lyon'],
        	  options: options
            })
```

**Comment by dipson88** [comment]
A problem is not related to listSlotHtmlComponent. listSlotHtmlComponent is an additional opportunity to add a component inside the list. Can you try to find styles for the list in a browser with help of inspect tool, maybe something with names of classes. Or you can try to add only list CSS from src folder and check the result.

**Comment by arpit1984** [comment]
class="treeselect-list treeselect-list--bottom-to-body treeselect-list--focused" is the style name for the dropdown which is coming out as transparent. 
I tried adding only list CSS from src folder, that removed the partial styling effect, so no effect at all.

**Comment by arpit1984** [comment]
My colleague figures out that why CSS was not coming into effect. The CSS is acting under shadow DOM, though the dropdown list comes (treeselect-list treeselect-list--bottom-to-body treeselect-list--focused) happens outside of the shadow DOM. I have to look into your package how you append the dropdown list and may be tweak it there

**Comment by dipson88** [comment]
I append the list of the elements inside the DOM container (parentHtmlContainer) with the help of append() method. If you use flag appendToBody = true - list will be appended to the end of the body tag.

**Comment by dipson88** [comment]
The list appends on focus (open) event and removes on blur (close) event.

**Comment by dipson88** [comment]
Closed as inactive. Specific behavior for the specific framework.
