### ISSUE TITLE
Option to allow only single select and disable some items to select

### ISSUE THREAD

**Issue by arpit1984** [dipson88/treeselectjs#23]
Would be nice to have to option of multi-select or just single select. In case of single select, there wont be any checkboxes.
Also, it would be good option to have the ability to disable some of the nodes so they cant be selected.

**Comment by dipson88** [comment]
@arpit1984 It is a nice idea! I am going to implement it in the features versions.

**Comment by dipson88** [comment]
Closed as partially completed.
Single select was implemented.
Disabled of nodes fix discussion moved to the issue - https://github.com/dipson88/treeselectjs/issues/41
