### ISSUE TITLE
Is there a way to select options on specific events?

### ISSUE THREAD

**Issue by burgieb** [dipson88/treeselectjs#24]
I want to to select values from the treeselect list based on a value selected in another dropdown. Is this possible?

Thanks!

**Comment by dipson88** [comment]
Hi @burgieb. So probably you can use method ```treeselect.updateValue(YOUR_NEW_VALUE)```. Call method when you want yo update value.
```updateValue | Array[String \| Number] | Update selected values.```

**Comment by burgieb** [comment]
Thanks @dipson88 it works
