### ISSUE TITLE
Possibility to add data-attributes

### ISSUE THREAD

**Issue by bastien70** [dipson88/treeselectjs#42]
Hey, is it possible to add to each option some data-attributes ? I think it could be a good feature

**Comment by dipson88** [comment]
Hi @bastien70. Do you want to add attributes inside the options? (name: '1', value: '1', ...some attributes)?
Do you want to set them as an HTML attribute or a result value on input?

**Comment by bastien70** [comment]
Hello, the idea would be to be able to add them in HTML.
Example : 

In the js file : 

```js
name: 'name 1',
value: 'value 1',
attr: {'data-foo': 'foo', 'data-bar': 'bar'}
```
