### ISSUE TITLE
Add option to keep only all childrens but not parent

### ISSUE THREAD

**Issue by bastien70** [dipson88/treeselectjs#43]
Take a look on this : 

![image](https://user-images.githubusercontent.com/53140475/199748940-f6f03431-8792-4971-93be-bfe6f117080e.png)

When you select "England" for example, the table of selected values ​​will correspond to the childrends of England, but in the input, it will be marked England.

It would be nice to have an option that instead, in this case, would list all the childrens rather than the parent
Like here https://www.jqueryscript.net/demo/Multi-Select-Checkbox-Tree-treeSelector/

**Comment by dipson88** [comment]
Hi @bastien70, what about ***grouped*** prop? This prop allows showing only children without groups if you set it to fasle. In your case, it will be Chelsea and West End.

**Comment by dipson88** [comment]
![image](https://user-images.githubusercontent.com/58396014/200369095-3040b20b-c4bf-445d-b3e5-46cded705e7f.png)

**Comment by dipson88** [comment]
I tried to use your example and add grouped: false at the end.

```const domElement = document.querySelector('.treeselect-demo')
const treeselect = new Treeselect({
  parentHtmlContainer: domElement,
  value: [],
  options: options,
  listSlotHtmlComponent: slot,
  placeholder: 'Rechercher ...',
  emptyText: 'Aucun résultat',
  disabledBranchNode: false,
  direction: 'auto', // auto, top, bottom
  id: 'treeselect_input',
  alwaysOpen: false,
  isGroupedValue: true,
  grouped: false
})

slot.addEventListener('click', (e) => {
  e.preventDefault()
  console.log(treeselect.value, treeselect.groupedValue)
})```

![image](https://user-images.githubusercontent.com/58396014/200875655-ae0885dc-f87b-43a9-9207-401cdd41886a.png)

**Comment by dipson88** [comment]
![image](https://user-images.githubusercontent.com/58396014/200876168-77fac5a3-3932-43e8-b53d-f7acd401eaa5.png)

**Comment by bastien70** [comment]
Oooooh okay, yes, you're right now :) Thank you :D

**Comment by dipson88** [comment]
Closed as completed.
