### ISSUE TITLE
Option customization

### ISSUE THREAD

**Issue by DmitrySur** [dipson88/treeselectjs#44]
Hello. Nice development, thanks. Is it possible to customize the display through the slot?
I have object:
`
  {
    name: 'my_name',
    value: 'my_value',
    icon: 'my_icon',
    children: []
}
`
And I would like to get out:
`<div><i class="my_icon"/>my_name</div>`

**Comment by dipson88** [comment]
Hello, @DmitrySur. Thank you for your good words!
Unfortunately, we don't have this opportunity, we can customize only the list slot at the end of the list. I can try to implement it in the feature.
But for now, I can suggest creating an element with an icon, inserting it into somewhere treeslect input area, and then changing the icon when the value changes.

**Comment by dipson88** [comment]
@DmitrySur I've added an example of how we can insert icons. Maybe it can help you. Check a 'Treeselect example with icons for appendToBody: false (workaround approach)' section - https://dipson88.github.io/treeselectjs/
