### ISSUE TITLE
React Wrapper

### ISSUE THREAD

**Issue by michelmar** [dipson88/treeselectjs#49]
Love what you are doing, do you have any plan in support a react package or wrapper?

**Comment by dipson88** [comment]
Hi @michelmar, thank you for your words. I created a Vue wrapper for my work project, in the near future I will share it too, and after that, I can make a react wrapper. But I can't say when it will be, probably as soon as possible.

**Comment by dipson88** [comment]
Hi, @michelmar, I've added a React Wrapper for my component.
You can find it here - https://www.npmjs.com/package/react-treeselectjs
It can have a couple of bugs (because I could miss something), but it works. Feel free to contact me if you have any issues.

**Comment by michelmar** [comment]
This is awesome, thanks. I'll take a look
