### ISSUE TITLE
How to add <optgroup> elements?

### ISSUE THREAD

**Issue by tacktack** [dipson88/treeselectjs#51]
How to add Options Group by using optgroup element in options?

**Comment by dipson88** [comment]
Hi, @tacktack, I didn't understand the question =) Notify me if I miss a question's meaning.

If you need a group use construction like:
```
[{
   name: 'group name', value: 123,
  children: [{ name: 'child', value: 321 }]
}]
```

if you need to disable groups - use `disabledBranchNode` prop. They will work like optgroup element
If you need to change styles - use classes.
