### ISSUE TITLE
e2e test

### ISSUE THREAD

**Issue by Joandres-Lara** [dipson88/treeselectjs#55]
Hi @dipson88, you have plains implement end to end integration tests?, I can do this, Cypress (https://docs.cypress.io/guides/overview/why-cypress) is a good framework for this, or you've another idea?

Regards.

**Comment by Joandres-Lara** [comment]
If you want it could start in a separate branch, like `integration`, installation and configuration is not hard.

**Comment by dipson88** [comment]
Base tests (Jest and Cypress) were added at https://github.com/dipson88/treeselectjs/pull/112
