### ISSUE TITLE
How to import treeselect on front end side ?

### ISSUE THREAD

**Issue by pbardou** [dipson88/treeselectjs#56]
Hello,

Sorry for this very general question but is there a .min.js file to import treeselect directly into a jquery single page with :
<script src="vendor/treeselect/treeselect.min.js"></script> ?

Thank you very much for this development and your help.

**Comment by dipson88** [comment]
Hi @pbardou, I used the parcel to create this library, as I know the parcel doesn't support script tag implementation (umd) at this moment, maybe they will add support or I will decide to use something else for the build. So we can't import packages this way. We need to use modules. (es module or commonjs).

**Comment by dipson88** [comment]
@pbardou, I updated a treeslect v0.8.0. Now you can use <script> tag. Check the README UMD section.
```
<script src="https://cdn.jsdelivr.net/npm/treeselectjs@0.8.0/dist/treeselectjs.umd.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/treeselectjs@0.8.0/dist/treeselectjs.css" />
...
<script>
  ...
  const treeselect = new Treeselect({ ...props })
  ...
</script>
```
