### ISSUE TITLE
get data instead of name

### ISSUE THREAD

**Issue by mbashirim** [dipson88/treeselectjs#58]
hi
in my case before using treeselectjs I had to make html menu and when something was selected I wanted element ID.
because I may have two elements with the same name but they can have different IDs.
can I get the id or number after selection changed?
to change data here :
treeselect.srcElement.addEventListener('input', (e) => {
        console.log('Selected value:', e.detail)
    })

**Comment by dipson88** [comment]
Hi @mbashirim, sorry for the late answer. I see, I don't update ```treeeselect.value``` filed, it always uses the default value.
After changing the value you can try to use ```treeeselect.value``` and it should contain a current value. But now it looks like a bug, I will fix it in a short term.
Did I understand your problem right?
