### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by mackhankins** [dipson88/treeselectjs#71]
How are people approaching lazy loading?  It seems like a must for larger datasets.

**Comment by dipson88** [comment]
Hello, @mackhankins. I'm sorry for not getting back to you sooner. At this moment I don't think about this. Now we need to use something like an around work. Maybe I can try to add an input text event or something like that, and you can use this event to detect loading. But I need to test it.

**Comment by dipson88** [comment]
@mackhankins I've added a **search** event and **searchCallback** prop (check documentation). It can help to implement something like lazy loading on your side.
