### ISSUE TITLE
Expand callback or emit?

### ISSUE THREAD

**Issue by mackhankins** [dipson88/treeselectjs#79]
I would like a way to track when a parent is expanded and return the "id" as a detail.

**Comment by CodeWithDennis** [comment]
This would be really useful!

**Comment by dipson88** [comment]
I will check an opportunity to do this, but it should not be very difficult to implement. I will do it in the short term.

**Comment by dipson88** [comment]
I've added open-close-group event and openCloseGroupCallback prop in version 0.9.3.
