### ISSUE TITLE
RTL not supported

### ISSUE THREAD

**Issue by omid1999** [dipson88/treeselectjs#83]
Thanks a lot for your great work. Please add right to left support for input and list both.

**Comment by dipson88** [comment]
@omid1999 Hi, thank you for your words! I will try to do it, but it can take a while and won't be fast.

**Comment by ariaieboy** [comment]
@dipson88 I've created a PR about this issue #84

**Comment by dipson88** [comment]
Was implemented in v0.10.0 (rtl prop).
